pipeline {
    agent any
    triggers {
        githubPush() // Esta línea activa el webhook de GitHub
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/astuek31/UCAM_CS.git', branch: 'master'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test' // Añadido un paso de prueba
            }
        }
    }
    post {
        success {
            echo 'Build completado con éxito'
        }
        failure {
            echo 'El build ha fallado'
        }
    }
}
