pipeline {
    agent any
    triggers {
        githubPush() // <- Añadido para asegurar que el Webhook se reconozca
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/astuek31/UCAM_CS.git', branch: 'master'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
    }
}
